/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32l476rg.h"

int main(void)
{
	RCC_Reg_t* pRCCReg = (RCC_Reg_t*)RCC_BASE_ADDRESS;
	GPIO_Reg_t* pGPIOCReg = (GPIO_Reg_t*)GPIOC;

	pRCCReg->RCC_AHB2ENR |= (1 << 2);

	for (int i = 0; i < 16; i++) {
		pGPIOCReg->MODER &= ~(0x2 << i * 2);
	}
//	pGPIOCReg->MODER |= (0x1 << 3 * 2);

    /* Loop forever */
	for(;;);
}
